
# name of the workflow
name: First Workflow

# workflow trigger event (worflow_dispatch allows to mannually trigger the workflow)
on: workflow_dispatch

jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: |
          echo "Multiline hello!"
          echo "Hello World!"
      - name: Print Goodbye
        run: |
          echo "Done - bye!"
          echo "Multiline bye!"

        
    
